// <auto-generated />
using System;
using Estatistica.DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estatistica.DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250815232634_change-logconcorrenteproduto")]
    partial class changelogconcorrenteproduto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.Concorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("conId");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtAlter");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtCadastro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("longtext")
                        .HasColumnName("usuAlter");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("longtext")
                        .HasColumnName("usuCadastro");

                    b.HasKey("Id");

                    b.ToTable("Concorrentes");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.ConcorrenteFilial", b =>
                {
                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cnpj");

                    b.Property<int>("ConcorrenteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtAlter");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtCadastro");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("longtext")
                        .HasColumnName("usuAlter");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("longtext")
                        .HasColumnName("usuCadastro");

                    b.HasKey("Cnpj");

                    b.HasIndex("ConcorrenteId");

                    b.ToTable("ConcorrenteFilials");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.ConcorrenteFilialPendente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cnpj");

                    b.Property<int?>("ConcorrenteId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<int?>("PlanilhaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConcorrenteId");

                    b.HasIndex("PlanilhaId");

                    b.ToTable("ConcorrenteFilialPendentes");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.ConcorrenteFilialTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cnpj");

                    b.Property<bool>("Incluido")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("incluido");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<int?>("PlanilhaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanilhaId");

                    b.ToTable("ConcorrenteFilialTemps");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.ConcorrenteProduto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoBarraConcorrente")
                        .HasColumnType("longtext")
                        .HasColumnName("codBarraCon");

                    b.Property<string>("CodigoProdutoConcorrente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("codProdCon");

                    b.Property<int>("ConcorrenteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtAlter");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtCadastro");

                    b.Property<string>("DescricaoProdutoConcorrente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descProdCon");

                    b.Property<int?>("PlanilhaId")
                        .HasColumnType("int");

                    b.Property<string>("ProdutoCodigoProduto")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TipoVinculo")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("tipoVinculo");

                    b.Property<string>("UnidadeProdutoConcorrente")
                        .HasColumnType("longtext")
                        .HasColumnName("unProdCon");

                    b.Property<string>("UsuarioAlteracao")
                        .HasColumnType("longtext")
                        .HasColumnName("usuAlter");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("longtext")
                        .HasColumnName("usuCadastro");

                    b.HasKey("Id");

                    b.HasIndex("ConcorrenteId");

                    b.HasIndex("PlanilhaId");

                    b.HasIndex("ProdutoCodigoProduto");

                    b.ToTable("ConcorrenteProdutos");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.LogConcorrenteProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CodigoBarraConcorrenteAnt")
                        .HasColumnType("longtext")
                        .HasColumnName("codBarraConAnt");

                    b.Property<string>("CodigoBarraConcorrenteAtual")
                        .HasColumnType("longtext")
                        .HasColumnName("codBarraConAtual");

                    b.Property<string>("CodigoProdutoAntCodigoProduto")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("CodigoProdutoAtualCodigoProduto")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("CodigoProdutoConcorrenteId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ConcorrenteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtCadastro");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtInclusao");

                    b.Property<string>("DescricaoProdutoConcorrenteAnt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descProdConAnt");

                    b.Property<string>("DescricaoProdutoConcorrenteAtual")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descProdConAtual");

                    b.Property<string>("Observacao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("obs");

                    b.Property<string>("UnidadeProdutoConcorrenteAnt")
                        .HasColumnType("longtext")
                        .HasColumnName("unProdConAnt");

                    b.Property<string>("UnidadeProdutoConcorrenteAtual")
                        .HasColumnType("longtext")
                        .HasColumnName("unProdConAtual");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("longtext")
                        .HasColumnName("usuCadastro");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoProdutoAntCodigoProduto");

                    b.HasIndex("CodigoProdutoAtualCodigoProduto");

                    b.HasIndex("CodigoProdutoConcorrenteId");

                    b.HasIndex("ConcorrenteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogConcorrenteProdutos");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.Nfc", b =>
                {
                    b.Property<string>("ChaveNfe")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("chaveNfe");

                    b.Property<string>("CnpjCliente")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("cnpjCliente");

                    b.Property<string>("ConcorrenteCnpjCnpj")
                        .HasColumnType("varchar(14)");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtCadastro");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtEmissao");

                    b.Property<string>("NomeCliente")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomeCliente");

                    b.Property<int?>("PlanilhaId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("longtext")
                        .HasColumnName("usuCadastro");

                    b.HasKey("ChaveNfe");

                    b.HasIndex("ConcorrenteCnpjCnpj");

                    b.HasIndex("PlanilhaId");

                    b.ToTable("Nfcs");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.Nfi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CodigoBarra")
                        .HasColumnType("longtext")
                        .HasColumnName("codBarra");

                    b.Property<string>("ConcorrenteProdutoId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtCadastro");

                    b.Property<string>("NfcChaveNfe")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Qtde")
                        .HasColumnType("int")
                        .HasColumnName("qtde");

                    b.Property<string>("UfDestino")
                        .HasColumnType("longtext")
                        .HasColumnName("ufDestino");

                    b.Property<string>("UfOrigin")
                        .HasColumnType("longtext")
                        .HasColumnName("ufOrigin");

                    b.Property<string>("Unidade")
                        .HasColumnType("longtext")
                        .HasColumnName("unidade");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("longtext")
                        .HasColumnName("usuCadastro");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("ConcorrenteProdutoId");

                    b.HasIndex("NfcChaveNfe");

                    b.ToTable("Nfis");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.Planilha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("planilhaId");

                    b.Property<string>("Caminho")
                        .HasColumnType("longtext")
                        .HasColumnName("caminho");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtCadastro");

                    b.Property<string>("NomePlanilha")
                        .HasColumnType("longtext")
                        .HasColumnName("nomePlanilha");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("UsuarioCadastro")
                        .HasColumnType("longtext")
                        .HasColumnName("usuCadastro");

                    b.HasKey("Id");

                    b.ToTable("Planilhas");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.PlanilhaStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataInclusao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtInclusao");

                    b.Property<string>("Obs")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("obs");

                    b.Property<int>("PlanhilaId")
                        .HasColumnType("int");

                    b.Property<int>("Situacao")
                        .HasColumnType("int")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.HasIndex("PlanhilaId");

                    b.ToTable("PlanilhaStatuses");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.Produto", b =>
                {
                    b.Property<string>("CodigoProduto")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("codProd");

                    b.Property<string>("CodigoBarra")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codBarra");

                    b.Property<string>("CodigoFabrica")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codFab");

                    b.Property<int?>("CodigoMarca")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("codMarca");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtCadastro");

                    b.Property<string>("Descricao")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("descricao");

                    b.Property<string>("DescricaoMarca")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("descMarca");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("fabricante");

                    b.Property<string>("Familia")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("familia");

                    b.Property<string>("Linha")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("linha");

                    b.Property<string>("SubTipo")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("subtipo");

                    b.Property<string>("Tipo")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("tipo");

                    b.Property<string>("Unidade")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("unidade");

                    b.HasKey("CodigoProduto");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ab4d57fd-d157-473b-b0e7-45aa9cb3b672",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "b24d88df-458b-4796-b226-b5ed67610dc6",
                            Name = "RCA",
                            NormalizedName = "RCA"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.ConcorrenteFilial", b =>
                {
                    b.HasOne("Estatistica.DataAccessLayer.Entities.Concorrente", "Concorrente")
                        .WithMany()
                        .HasForeignKey("ConcorrenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concorrente");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.ConcorrenteFilialPendente", b =>
                {
                    b.HasOne("Estatistica.DataAccessLayer.Entities.Concorrente", "Concorrente")
                        .WithMany()
                        .HasForeignKey("ConcorrenteId");

                    b.HasOne("Estatistica.DataAccessLayer.Entities.Planilha", "Planilha")
                        .WithMany()
                        .HasForeignKey("PlanilhaId");

                    b.Navigation("Concorrente");

                    b.Navigation("Planilha");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.ConcorrenteFilialTemp", b =>
                {
                    b.HasOne("Estatistica.DataAccessLayer.Entities.Planilha", "Planilha")
                        .WithMany()
                        .HasForeignKey("PlanilhaId");

                    b.Navigation("Planilha");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.ConcorrenteProduto", b =>
                {
                    b.HasOne("Estatistica.DataAccessLayer.Entities.Concorrente", "Concorrente")
                        .WithMany()
                        .HasForeignKey("ConcorrenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estatistica.DataAccessLayer.Entities.Planilha", "Planilha")
                        .WithMany()
                        .HasForeignKey("PlanilhaId");

                    b.HasOne("Estatistica.DataAccessLayer.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoCodigoProduto");

                    b.Navigation("Concorrente");

                    b.Navigation("Planilha");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.LogConcorrenteProduto", b =>
                {
                    b.HasOne("Estatistica.DataAccessLayer.Entities.Produto", "CodigoProdutoAnt")
                        .WithMany()
                        .HasForeignKey("CodigoProdutoAntCodigoProduto");

                    b.HasOne("Estatistica.DataAccessLayer.Entities.Produto", "CodigoProdutoAtual")
                        .WithMany()
                        .HasForeignKey("CodigoProdutoAtualCodigoProduto");

                    b.HasOne("Estatistica.DataAccessLayer.Entities.ConcorrenteProduto", "CodigoProdutoConcorrente")
                        .WithMany()
                        .HasForeignKey("CodigoProdutoConcorrenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estatistica.DataAccessLayer.Entities.Concorrente", "Concorrente")
                        .WithMany()
                        .HasForeignKey("ConcorrenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("CodigoProdutoAnt");

                    b.Navigation("CodigoProdutoAtual");

                    b.Navigation("CodigoProdutoConcorrente");

                    b.Navigation("Concorrente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.Nfc", b =>
                {
                    b.HasOne("Estatistica.DataAccessLayer.Entities.ConcorrenteFilial", "ConcorrenteCnpj")
                        .WithMany()
                        .HasForeignKey("ConcorrenteCnpjCnpj");

                    b.HasOne("Estatistica.DataAccessLayer.Entities.Planilha", "Planilha")
                        .WithMany()
                        .HasForeignKey("PlanilhaId");

                    b.Navigation("ConcorrenteCnpj");

                    b.Navigation("Planilha");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.Nfi", b =>
                {
                    b.HasOne("Estatistica.DataAccessLayer.Entities.ConcorrenteProduto", "ConcorrenteProduto")
                        .WithMany()
                        .HasForeignKey("ConcorrenteProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Estatistica.DataAccessLayer.Entities.Nfc", "Nfc")
                        .WithMany()
                        .HasForeignKey("NfcChaveNfe");

                    b.Navigation("ConcorrenteProduto");

                    b.Navigation("Nfc");
                });

            modelBuilder.Entity("Estatistica.DataAccessLayer.Entities.PlanilhaStatus", b =>
                {
                    b.HasOne("Estatistica.DataAccessLayer.Entities.Planilha", "Planhila")
                        .WithMany()
                        .HasForeignKey("PlanhilaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planhila");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
