name: Deploy Connection Test

on:
  push:
    branches:
      - dev
      - master

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "SSH connection successful"
            echo "User:"
            whoami
            echo "Hostname:"
            hostname